apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: docker.io/cloudattech/django-example-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_ENGINE
          value: "postgresql"
        - name: DATABASE_HOST
          value: "my-postgresdb.postgres.database.azure.com"
        - name: DATABASE_USER
          value: "prizejay1"
        - name: DATABASE_PASSWORD
          value: "r0VHS2s_HCnKYTgmyFTqUg"
        - name: DATABASE_NAME
          value: "flexibleserverdb"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - django-app
              topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  name: python-svc
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: django-app
